---
# Ansible Galaxy requirements for Linux VM Health Check
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=6.0.0"

roles: []
  # Add any required roles here if needed in the future
  # - name: geerlingguy.security
  #   version: "1.0.0"